export const SET_EXPIRED_TYPE = 'SET_EXPIRED_TYPE'
export const SET_EXPIRED_START = 'SET_EXPIRED_START'
export const SET_EXPIRED_END = 'SET_EXPIRED_END'
export const SET_COUPOU_EXPIRED = 'SET_COUPOU_EXPIRED'

export const SET_USE_TIMES = 'SET_USE_TIMES'
export const SET_USE_TIME_DAY = 'SET_USE_TIME_DAY'
