export const RESET_ALL_STATE = 'RESET_ALL_STATE'

export const SET_EXPIRED_TYPE = 'SET_EXPIRED_TYPE'
export const SET_EXPIRED_START = 'SET_EXPIRED_START'
export const SET_EXPIRED_END = 'SET_EXPIRED_END'
export const SET_COUPOU_EXPIRED = 'SET_COUPOU_EXPIRED'

export const UPDATE_USE_TIME = 'UPDATE_USE_TIME'
export const DELETE_USE_TIME = 'DELETE_USE_TIME'
export const CLEAR_USE_TIME = 'CLEAR_USE_TIME'

export const INIT_USE_TIME_ITEM = 'INIT_USE_TIME_ITEM'
export const UPDATE_RESULT_USE_TIME = 'UPDATE_RESULT_USE_TIME'

export const UPDATE_USE_INSTRUCTIONS = 'UPDATE_USE_INSTRUCTIONS'

export const SET_SHOPS = 'SET_SHOPS'

export const SET_DISCOUNT1_OTHER = 'SET_DISCOUNT1_OTHER'

export const SET_QINIU_URL = 'SET_QINIU_URL'
export const SET_IMG_ID = 'SET_IMG_ID'
